# -*- coding: utf-8 -*-
import os

BT = chr(96)  # backtick
BT3 = BT * 3  # ```

lines = []
lines.append('# 变更冻结例外审批 API')
lines.append('')
lines.append('本地可运行的变更冻结例外审批系统，基于 Flask + SQLite 实现。')
lines.append('')
lines.append('## 目录结构')
lines.append('')
lines.append(BT3)
lines.append('├── app/')
lines.append('│   ├── __init__.py          # Flask 应用工厂')
lines.append('│   ├── models.py            # 数据模型 (SQLAlchemy)')
lines.append('│   ├── storage.py           # 存储层 (CRUD)')
lines.append('│   ├── state_validator.py   # 状态校验层 (状态机、冲突检测)')
lines.append('│   ├── permissions.py       # 权限判断层 (角色权限)')
lines.append('│   └── routes.py            # 路由层 (API 端点)')
lines.append('├── init_db.py               # 数据库初始化脚本')
lines.append('├── run.py                   # 主入口')
lines.append('├── requirements.txt         # 依赖')
lines.append('└── README.md                # 本文档')
lines.append(BT3)
lines.append('')
lines.append('## 本地启动方式')
lines.append('')
lines.append('### 1. 安装依赖')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('pip install -r requirements.txt')
lines.append(BT3)
lines.append('')
lines.append('### 2. 启动服务')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('python run.py')
lines.append(BT3)
lines.append('')
lines.append(f'服务将在 {BT}http://127.0.0.1:5000{BT} 启动，首次启动会自动初始化数据库并创建示例数据。')
lines.append('')
lines.append('### 3. 初始化数据')
lines.append('')
lines.append('启动时自动创建以下数据：')
lines.append('')
lines.append('**角色:**')
lines.append(f'- {BT}APPLICANT{BT} (申请人): zhangsan, lisi')
lines.append(f'- {BT}REVIEWER{BT} (风险复核人): wangwu, zhaoliu')
lines.append(f'- {BT}APPROVER{BT} (审批人): qianqi, sunba')
lines.append('')
lines.append('**系统:**')
lines.append(f'- {BT}PAYMENT-SYSTEM{BT} (核心支付系统)')
lines.append(f'- {BT}USER-SERVICE{BT} (用户中心服务)')
lines.append(f'- {BT}ORDER-SYSTEM{BT} (订单系统)')
lines.append(f'- {BT}INVENTORY-SYSTEM{BT} (库存系统)')
lines.append('')
lines.append('## 状态图')
lines.append('')
lines.append(BT3)
lines.append('                       ┌─────────────────┐')
lines.append('                       │ PENDING_REVIEW  │  待复核（初始状态）')
lines.append('                       └────────┬────────┘')
lines.append('                                │')
lines.append('          ┌─────────────────────┼─────────────────────┐')
lines.append('          ▼                     ▼                     ▼')
lines.append('┌─────────────────┐   ┌─────────────────┐   ┌─────────────────┐')
lines.append('│    REVIEWED     │   │ REVIEW_REJECTED │   │   WITHDRAWN     │')
lines.append('│   （复核通过）  │   │  （复核拒绝）   │   │   （已撤回）    │')
lines.append('└────────┬────────┘   └─────────────────┘   └─────────────────┘')
lines.append('          │                                    （终态，不可再变更）')
lines.append('          ▼')
lines.append('┌─────────────────┐')
lines.append('│    APPROVED     │')
lines.append('│   （已批准）    │')
lines.append('└────────┬────────┘')
lines.append('          │')
lines.append('          ▼')
lines.append('┌─────────────────┐')
lines.append('│   EFFECTIVE     │  （已生效）')
lines.append('└─────────────────┘')
lines.append(BT3)
lines.append('')
lines.append('### 状态转换规则')
lines.append('')
lines.append('| 当前状态         | 允许转换到                    | 操作角色     |')
lines.append('|------------------|-----------------------------|------------|')
lines.append('| PENDING_REVIEW   | REVIEWED, REVIEW_REJECTED, WITHDRAWN | REVIEWER(复核)/APPLICANT(撤回) |')
lines.append('| REVIEWED         | APPROVED, REVIEW_REJECTED, WITHDRAWN | APPROVER(审批)/APPLICANT(撤回) |')
lines.append('| REVIEW_REJECTED  | WITHDRAWN                   | APPLICANT  |')
lines.append('| APPROVED         | EFFECTIVE, WITHDRAWN        | APPROVER(生效)/APPLICANT(撤回) |')
lines.append('| EFFECTIVE        | WITHDRAWN                   | APPLICANT  |')
lines.append('| WITHDRAWN        | -                           | -          |')
lines.append('')
lines.append('## API 接口')
lines.append('')
lines.append(f'所有接口前缀: {BT}/api{BT}')
lines.append('')
lines.append('### 基础查询')
lines.append('')
lines.append('#### 获取角色列表')
lines.append(BT3 + 'bash')
lines.append('curl http://127.0.0.1:5000/api/roles')
lines.append(BT3)
lines.append('')
lines.append('#### 获取系统列表')
lines.append(BT3 + 'bash')
lines.append('curl http://127.0.0.1:5000/api/systems')
lines.append(BT3)
lines.append('')
lines.append('#### 获取用户列表')
lines.append(BT3 + 'bash')
lines.append('curl http://127.0.0.1:5000/api/users')
lines.append(BT3)
lines.append('')
lines.append('#### 获取所有申请')
lines.append(BT3 + 'bash')
lines.append('curl "http://127.0.0.1:5000/api/requests?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('#### 获取单个申请详情')
lines.append(BT3 + 'bash')
lines.append('curl "http://127.0.0.1:5000/api/requests/1?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('### 主流程')
lines.append('')
lines.append('#### 1. 申请人提交申请')
lines.append(BT3 + 'bash')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "zhangsan",')
lines.append('    "system_id": "PAYMENT-SYSTEM",')
lines.append('    "window_start": "2026-06-10T00:00:00Z",')
lines.append('    "window_end": "2026-06-15T23:59:59Z",')
lines.append('    "risk_level": "MEDIUM",')
lines.append('    "reason": "紧急修复支付网关漏洞，需要在冻结期间上线"')
lines.append("  }'")
lines.append(BT3)
lines.append('')
lines.append('**返回示例 (成功):**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "message": "申请提交成功",')
lines.append('  "data": {')
lines.append('    "id": 1,')
lines.append('    "status": "PENDING_REVIEW",')
lines.append('    "risk_level": "MEDIUM",')
lines.append('    "window_start": "2026-06-10T00:00:00Z",')
lines.append('    "window_end": "2026-06-15T23:59:59Z"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('#### 2. 风险复核人复核')
lines.append(BT3 + 'bash')
lines.append('# 复核通过')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/review \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "wangwu",')
lines.append('    "approved": true,')
lines.append('    "comment": "风险可控，已有回滚方案，同意"')
lines.append("  }'")
lines.append('')
lines.append('# 复核拒绝')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/review \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "wangwu",')
lines.append('    "approved": false,')
lines.append('    "comment": "风险过高，建议延后到冻结期后"')
lines.append("  }'")
lines.append(BT3)
lines.append('')
lines.append('#### 3. 审批人批准')
lines.append(BT3 + 'bash')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/approve \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "qianqi",')
lines.append('    "comment": "同意，安排在凌晨低峰期执行"')
lines.append("  }'")
lines.append(BT3)
lines.append('')
lines.append('#### 4. 审批人生效')
lines.append(BT3 + 'bash')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/effective \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "qianqi",')
lines.append('    "comment": "变更已执行并验证通过"')
lines.append("  }'")
lines.append(BT3)
lines.append('')
lines.append('#### 5. 申请人撤回')
lines.append(BT3 + 'bash')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/withdraw \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "zhangsan",')
lines.append('    "comment": "问题已通过其他方式解决，撤回申请"')
lines.append("  }'")
lines.append(BT3)
lines.append('')
lines.append('> **重要**: 撤回是终态操作。申请一旦撤回，状态保持为 WITHDRAWN，无法再次批准、生效或通过任何接口修改，审计历史也不会新增记录。如需重新申请，请创建新的变更申请。')
lines.append('')
lines.append('### 审计记录')
lines.append('')
lines.append('#### 查询全部审计日志')
lines.append(BT3 + 'bash')
lines.append('curl "http://127.0.0.1:5000/api/audit?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('#### 按申请ID过滤审计日志')
lines.append('')
lines.append(f'**接口格式:** {BT}/api/audit?username=...&request_id=...{BT}')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('# 只返回指定申请的审计记录')
lines.append('curl "http://127.0.0.1:5000/api/audit?username=zhangsan&request_id=1"')
lines.append(BT3)
lines.append('')
lines.append('**参数说明:**')
lines.append(f'- {BT}username{BT}: 必需，用于权限验证')
lines.append(f'- {BT}request_id{BT}: 可选，整数，用于过滤指定申请的审计记录')
lines.append('  - 不传或传空值：返回全量审计记录')
lines.append(f'  - 传非整数：返回 400 错误 {BT}INVALID_REQUEST_ID{BT}')
lines.append(f'  - 传不存在的申请ID：返回 404 错误 {BT}REQUEST_NOT_FOUND{BT}')
lines.append('')
lines.append('#### 查询单个申请的状态历史')
lines.append(BT3 + 'bash')
lines.append('curl "http://127.0.0.1:5000/api/requests/1/history?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('**返回示例:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "data": [')
lines.append('    {')
lines.append('      "id": 1,')
lines.append('      "request_id": 1,')
lines.append('      "from_status": null,')
lines.append('      "to_status": "PENDING_REVIEW",')
lines.append('      "operator": {"username": "zhangsan", "role": "APPLICANT"},')
lines.append('      "comment": "提交申请",')
lines.append('      "created_at": "2026-06-05T10:30:00Z"')
lines.append('    },')
lines.append('    {')
lines.append('      "id": 2,')
lines.append('      "request_id": 1,')
lines.append('      "from_status": "PENDING_REVIEW",')
lines.append('      "to_status": "REVIEWED",')
lines.append('      "operator": {"username": "wangwu", "role": "REVIEWER"},')
lines.append('      "comment": "风险可控",')
lines.append('      "created_at": "2026-06-05T11:00:00Z"')
lines.append('    }')
lines.append('  ]')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('## 导入导出')
lines.append('')
lines.append('### CSV 字段说明')
lines.append('')
lines.append('导入导出使用 UTF-8 编码的 CSV 文件，包含以下字段：')
lines.append('')
lines.append('| 字段名     | 必填 | 说明                                                                 |')
lines.append('|------------|------|----------------------------------------------------------------------|')
lines.append(f'| 标题       | 是   | 变更申请的标题，最长 200 字符                                        |')
lines.append(f'| 系统       | 是   | 系统名称，必须是已存在的系统（如 {BT}PAYMENT-SYSTEM{BT}, {BT}USER-SERVICE{BT} 等）|')
lines.append(f'| 窗口开始   | 是   | 窗口期开始时间，格式：{BT}YYYY-MM-DDTHH:MM:SSZ{BT}（UTC 时间）             |')
lines.append(f'| 窗口结束   | 是   | 窗口期结束时间，格式：{BT}YYYY-MM-DDTHH:MM:SSZ{BT}（UTC 时间），必须晚于开始时间 |')
lines.append(f'| 风险等级   | 是   | 风险等级，可选值：{BT}LOW{BT}, {BT}MEDIUM{BT}, {BT}HIGH{BT}                            |')
lines.append(f'| 风险说明   | 是   | 变更的原因和风险说明，最长 1000 字符                                  |')
lines.append(f'| 备注       | 否   | 额外备注信息，最长 500 字符                                          |')
lines.append('')
lines.append('### CSV 示例（可直接保存使用）')
lines.append('')
lines.append(f'将以下内容保存为 {BT}import_example.csv{BT}（注意使用 UTF-8 编码）：')
lines.append('')
lines.append(BT3 + 'csv')
lines.append('标题,系统,窗口开始,窗口结束,风险等级,风险说明,备注')
lines.append('支付网关安全升级,PAYMENT-SYSTEM,2026-06-20T00:00:00Z,2026-06-25T23:59:59Z,HIGH,紧急修复支付网关安全漏洞,需凌晨执行')
lines.append('用户中心性能优化,USER-SERVICE,2026-07-01T00:00:00Z,2026-07-05T23:59:59Z,MEDIUM,优化用户查询接口性能,')
lines.append('订单系统Bug修复,ORDER-SYSTEM,2026-07-10T00:00:00Z,2026-07-15T23:59:59Z,LOW,修复订单状态同步问题,低风险变更')
lines.append(BT3)
lines.append('')
lines.append('### 导出申请')
lines.append('')
lines.append(f'**权限要求**: {BT}APPLICANT{BT}, {BT}REVIEWER{BT}, {BT}APPROVER{BT}')
lines.append('- 申请人只能导出自己的申请')
lines.append('- 复核人、审批人可以导出所有申请')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('# 导出所有可见申请（CSV 格式）')
lines.append('curl -o change_requests.csv "http://127.0.0.1:5000/api/requests/export?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('**成功响应** (HTTP 200):')
lines.append(BT3)
lines.append('Content-Type: text/csv; charset=utf-8-sig')
lines.append('Content-Disposition: attachment; filename=change_requests_20260605_120000.csv')
lines.append('')
lines.append('标题,系统,窗口开始,窗口结束,风险等级,风险说明,备注')
lines.append('支付网关安全升级,PAYMENT-SYSTEM,2026-06-20T00:00:00Z,2026-06-25T23:59:59Z,HIGH,紧急修复支付网关安全漏洞,需凌晨执行')
lines.append('...')
lines.append(BT3)
lines.append('')
lines.append('**权限拒绝响应** (HTTP 403):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "USER_NOT_FOUND",')
lines.append('    "message": "用户不存在: invalid_user"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 批量导入申请')
lines.append('')
lines.append(f'**权限要求**: {BT}APPLICANT{BT}（仅申请人可导入）')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('# 从 CSV 文件批量导入申请')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/import \\')
lines.append('  -F "username=zhangsan" \\')
lines.append('  -F "file=@import_example.csv;type=text/csv"')
lines.append(BT3)
lines.append('')
lines.append('**全部成功响应** (HTTP 200):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "message": "导入完成：成功 3 条，失败 0 条",')
lines.append('  "data": {')
lines.append('    "batch_no": "IMP_20260605120000_a1b2c3d4",')
lines.append('    "total_count": 3,')
lines.append('    "success_count": 3,')
lines.append('    "fail_count": 0,')
lines.append('    "success_ids": [101, 102, 103],')
lines.append('    "failed_rows": []')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('**部分失败响应** (HTTP 200):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "message": "导入完成：成功 2 条，失败 1 条",')
lines.append('  "data": {')
lines.append('    "batch_no": "IMP_20260605120000_a1b2c3d4",')
lines.append('    "total_count": 3,')
lines.append('    "success_count": 2,')
lines.append('    "fail_count": 1,')
lines.append('    "success_ids": [101, 103],')
lines.append('    "failed_rows": [')
lines.append('      {')
lines.append('        "row": 3,')
lines.append('        "code": "SYSTEM_NOT_FOUND",')
lines.append('        "message": "系统不存在: INVALID-SYSTEM"')
lines.append('      }')
lines.append('    ]')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('**权限拒绝响应** (HTTP 403):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "ROLE_PERMISSION_DENIED",')
lines.append('    "message": "角色 \"风险复核人\" 无权执行此操作。允许的角色: 申请人"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('**CSV 格式错误响应** (HTTP 400):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "MISSING_COLUMN",')
lines.append('    "message": "缺少必填列: 风险等级"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 查询导入批次列表')
lines.append('')
lines.append(f'**权限要求**: {BT}APPLICANT{BT}, {BT}REVIEWER{BT}, {BT}APPROVER{BT}')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('curl "http://127.0.0.1:5000/api/import/batches?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('**成功响应** (HTTP 200):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "data": [')
lines.append('    {')
lines.append('      "id": 1,')
lines.append('      "batch_no": "IMP_20260605120000_a1b2c3d4",')
lines.append('      "operator": {')
lines.append('        "id": 1,')
lines.append('        "username": "zhangsan",')
lines.append('        "role": "APPLICANT"')
lines.append('      },')
lines.append('      "total_count": 3,')
lines.append('      "success_count": 2,')
lines.append('      "fail_count": 1,')
lines.append('      "created_at": "2026-06-05T12:00:00Z"')
lines.append('    }')
lines.append('  ]')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 查询批次详情（明细）')
lines.append('')
lines.append(f'**权限要求**: {BT}APPLICANT{BT}, {BT}REVIEWER{BT}, {BT}APPROVER{BT}')
lines.append('')
lines.append(BT3 + 'bash')
lines.append('# 使用批次号查询明细')
lines.append('curl "http://127.0.0.1:5000/api/import/batches/IMP_20260605120000_a1b2c3d4/records?username=zhangsan"')
lines.append(BT3)
lines.append('')
lines.append('**成功响应** (HTTP 200):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "data": {')
lines.append('    "batch": {')
lines.append('      "id": 1,')
lines.append('      "batch_no": "IMP_20260605120000_a1b2c3d4",')
lines.append('      "operator": {')
lines.append('        "id": 1,')
lines.append('        "username": "zhangsan",')
lines.append('        "role": "APPLICANT"')
lines.append('      },')
lines.append('      "total_count": 3,')
lines.append('      "success_count": 2,')
lines.append('      "fail_count": 1,')
lines.append('      "created_at": "2026-06-05T12:00:00Z"')
lines.append('    },')
lines.append('    "records": [')
lines.append('      {')
lines.append('        "row_no": 2,')
lines.append('        "success": true,')
lines.append('        "error_code": null,')
lines.append('        "error_message": null,')
lines.append('        "request_id": 101')
lines.append('      },')
lines.append('      {')
lines.append('        "row_no": 3,')
lines.append('        "success": false,')
lines.append('        "error_code": "SYSTEM_NOT_FOUND",')
lines.append('        "error_message": "系统不存在: INVALID-SYSTEM",')
lines.append('        "request_id": null')
lines.append('      },')
lines.append('      {')
lines.append('        "row_no": 4,')
lines.append('        "success": true,')
lines.append('        "error_code": null,')
lines.append('        "error_message": null,')
lines.append('        "request_id": 103')
lines.append('      }')
lines.append('    ]')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('**批次不存在响应** (HTTP 404):')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "BATCH_NOT_FOUND",')
lines.append('    "message": "批次不存在: IMP_INVALID"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 窗口冲突场景说明')
lines.append('')
lines.append(f'导入时，如果某行数据的窗口期与同一系统已批准/已生效的申请窗口重叠，该行会失败（返回 {BT}WINDOW_CONFLICT{BT} 错误），但其他合法行仍会成功落库。')
lines.append('')
lines.append('**示例响应**（第 3 行冲突）:')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": true,')
lines.append('  "message": "导入完成：成功 2 条，失败 1 条",')
lines.append('  "data": {')
lines.append('    "batch_no": "IMP_20260605120000_e5f6g7h8",')
lines.append('    "total_count": 3,')
lines.append('    "success_count": 2,')
lines.append('    "fail_count": 1,')
lines.append('    "success_ids": [104, 106],')
lines.append('    "failed_rows": [')
lines.append('      {')
lines.append('        "row": 3,')
lines.append('        "code": "WINDOW_CONFLICT",')
lines.append('        "message": "该系统在申请的窗口期内已有已批准或已生效的变更冻结例外，窗口重叠"')
lines.append('      }')
lines.append('    ]')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('## 失败路径测试')
lines.append('')
lines.append('### 1. 非法角色操作')
lines.append(BT3 + 'bash')
lines.append('# 申请人尝试审批')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/approve \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{\"username\": \"zhangsan\"}'")
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "ROLE_PERMISSION_DENIED",')
lines.append('    "message": "角色 \"申请人\" 无权执行此操作。允许的角色: 审批人"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 2. 未复核就审批')
lines.append(BT3 + 'bash')
lines.append('# 申请状态为 PENDING_REVIEW 时直接审批')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/approve \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{\"username\": \"qianqi\"}'")
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "NOT_REVIEWED",')
lines.append('    "message": "申请尚未经过风险复核，审批人无法批准。请先由复核人进行风险复核"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 3. 窗口期重叠')
lines.append(BT3 + 'bash')
lines.append('# 先创建一个已批准的申请')
lines.append('# 再创建另一个窗口期重叠的申请')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{")
lines.append('    "username": "lisi",')
lines.append('    "system_id": "PAYMENT-SYSTEM",')
lines.append('    "window_start": "2026-06-12T00:00:00Z",')
lines.append('    "window_end": "2026-06-20T23:59:59Z",')
lines.append('    "risk_level": "HIGH",')
lines.append('    "reason": "另一个变更申请"')
lines.append("  }'")
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "WINDOW_CONFLICT",')
lines.append('    "message": "该系统在申请的窗口期内已有已批准或已生效的变更冻结例外，窗口重叠"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 4. 撤回后尝试再次批准')
lines.append(BT3 + 'bash')
lines.append('# 申请状态为 WITHDRAWN 时尝试再次批准')
lines.append('curl -X POST http://127.0.0.1:5000/api/requests/1/re-effective \\')
lines.append('  -H "Content-Type: application/json" \\')
lines.append("  -d '{\"username\": \"qianqi\"}'")
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "WITHDRAWN_FINAL_STATE",')
lines.append('    "message": "申请已撤回，是终态，无法再次批准或生效。如需重新申请，请创建新的变更申请"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 5. 审计查询使用无效的 request_id')
lines.append(BT3 + 'bash')
lines.append('# 使用非整数的 request_id')
lines.append('curl "http://127.0.0.1:5000/api/audit?username=zhangsan&request_id=abc"')
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "INVALID_REQUEST_ID",')
lines.append('    "message": "request_id 参数无效，必须是整数: abc"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('### 6. 审计查询使用不存在的 request_id')
lines.append(BT3 + 'bash')
lines.append('# 使用不存在的 request_id')
lines.append('curl "http://127.0.0.1:5000/api/audit?username=zhangsan&request_id=99999"')
lines.append(BT3)
lines.append('**返回错误:**')
lines.append(BT3 + 'json')
lines.append('{')
lines.append('  "success": false,')
lines.append('  "error": {')
lines.append('    "code": "REQUEST_NOT_FOUND",')
lines.append('    "message": "申请不存在: 99999"')
lines.append('  }')
lines.append('}')
lines.append(BT3)
lines.append('')
lines.append('## 数据持久化')
lines.append('')
lines.append(f'所有数据保存在 SQLite 数据库文件 {BT}instance/change_freeze.db{BT} 中（与 Flask 配置一致，位于项目根目录下的 {BT}instance{BT} 文件夹）：')
lines.append('')
lines.append(f'- {BT}roles{BT}: 角色表')
lines.append(f'- {BT}systems{BT}: 系统表')
lines.append(f'- {BT}users{BT}: 用户表（关联角色）')
lines.append(f'- {BT}change_requests{BT}: 变更申请表')
lines.append(f'- {BT}import_batches{BT}: 导入批次表')
lines.append(f'- {BT}import_records{BT}: 导入明细表（每行导入结果）')
lines.append(f'- {BT}status_history{BT}: 状态历史表（审计日志）')
lines.append('')
lines.append('重启服务后，所有申请状态、导入批次、状态历史和冲突判断都将保持一致。')
lines.append('')
lines.append('## 错误码说明')
lines.append('')
lines.append('| 错误码 | 说明 |')
lines.append('|-------|------|')
lines.append(f'| {BT}INVALID_STATUS{BT} | 无效的状态值 |')
lines.append(f'| {BT}INVALID_TRANSITION{BT} | 不允许的状态转换 |')
lines.append(f'| {BT}INVALID_RISK_LEVEL{BT} | 无效的风险等级 |')
lines.append(f'| {BT}INVALID_DATETIME_FORMAT{BT} | 日期时间格式错误 |')
lines.append(f'| {BT}INVALID_WINDOW_RANGE{BT} | 窗口期时间范围无效 |')
lines.append(f'| {BT}WINDOW_CONFLICT{BT} | 窗口期与已批准/已生效申请重叠 |')
lines.append(f'| {BT}NOT_REVIEWED{BT} | 未经过风险复核 |')
lines.append(f'| {BT}REVIEW_REJECTED{BT} | 已被复核拒绝 |')
lines.append(f'| {BT}ALREADY_EFFECTIVE{BT} | 已生效，无法撤回 |')
lines.append(f'| {BT}WITHDRAWN_FINAL_STATE{BT} | 申请已撤回，是终态，无法再次批准或生效。状态保持 WITHDRAWN，审计历史不新增记录 |')
lines.append(f'| {BT}INVALID_REQUEST_ID{BT} | request_id 参数无效，必须是整数 |')
lines.append(f'| {BT}USER_NOT_FOUND{BT} | 用户不存在 |')
lines.append(f'| {BT}ROLE_PERMISSION_DENIED{BT} | 角色无权限 |')
lines.append(f'| {BT}NOT_APPLICANT{BT} | 非申请人本人 |')
lines.append(f'| {BT}APPLICANT_CANNOT_REVIEW{BT} | 申请人不能复核自己的申请 |')
lines.append(f'| {BT}APPLICANT_CANNOT_APPROVE{BT} | 申请人不能批准自己的申请 |')
lines.append(f'| {BT}SYSTEM_NOT_FOUND{BT} | 系统不存在 |')
lines.append(f'| {BT}REQUEST_NOT_FOUND{BT} | 申请不存在 |')
lines.append(f'| {BT}MISSING_FILE{BT} | 缺少上传文件 |')
lines.append(f'| {BT}EMPTY_FILENAME{BT} | 文件名为空 |')
lines.append(f'| {BT}INVALID_FILE_FORMAT{BT} | 文件格式无效，只支持 CSV |')
lines.append(f'| {BT}MISSING_COLUMN{BT} | CSV 缺少必填列 |')
lines.append(f'| {BT}EMPTY_FILE{BT} | CSV 文件为空 |')
lines.append(f'| {BT}MISSING_TITLE{BT} | 标题不能为空 |')
lines.append(f'| {BT}MISSING_SYSTEM{BT} | 系统不能为空 |')
lines.append(f'| {BT}MISSING_WINDOW_START{BT} | 窗口开始不能为空 |')
lines.append(f'| {BT}MISSING_WINDOW_END{BT} | 窗口结束不能为空 |')
lines.append(f'| {BT}MISSING_RISK_LEVEL{BT} | 风险等级不能为空 |')
lines.append(f'| {BT}MISSING_REASON{BT} | 风险说明不能为空 |')
lines.append(f'| {BT}BATCH_NOT_FOUND{BT} | 导入批次不存在 |')
lines.append('')

content = '\n'.join(lines) + '\n'

with open('README.md', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('README written successfully!')
print('Size:', len(content))

# 验证关键内容
with open('README.md', 'rb') as f:
    check = f.read()

bt3 = chr(96) * 3
print(f'Has instance/change_freeze.db:', b'instance/change_freeze.db' in check)
print(f'Has 导入导出:', '导入导出'.encode('utf-8') in check)
print(f'Has CSV 字段说明:', 'CSV 字段说明'.encode('utf-8') in check)
print(f'Has {bt3}csv:', (bt3 + 'csv').encode('utf-8') in check)
print(f'Has 标题,系统,窗口开始:', '标题,系统,窗口开始'.encode('utf-8') in check)
